export const ROUTE = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  REGISTER_BY_INVITE: '/signup-by-invitation/:token',
  SCHEDULES: '/schedules',
  FINANCES: '/finances',
  NOTES: '/notes',
  TASKS: '/tasks',
  BONUSES: '/bonuses',
  ACTIVITIES: '/activities',
  SETTINGS: '/settings',
  ERROR: '/error',
};
