export const FINANCE_TYPE = {
  INCOME: 'INCOME',
  OUTCOME: 'OUTCOME',
};

export const FINANCE_TAB = {
  STATEMENTS: 'STATEMENTS',
  STATISTICS: 'STATISTICS',
};

export const FINANCE_STATISTICS_TYPE = {
  FULL: 'FULL',
  BY_DAY: 'BY_DAY',
};
