export const MODAL_NAME = {
  CREATE_SCHEDULE: 'CREATE_SCHEDULE',
  SCHEDULE_DETAILS: 'SCHEDULE_DETAILS',
  EDIT_SCHEDULE: 'EDIT_SCHEDULE',
  MANAGE_PARTICIPANTS: 'MANAGE_PARTICIPANTS',
  LEAVE_SCHEDULE: 'LEAVE_SCHEDULE',
  DELETE_SCHEDULE: 'DELETE_SCHEDULE',
};
