export const MODAL_NAME = {
  CREATE_SCHEDULE: 'schedule/CREATE_SCHEDULE',
  SCHEDULE_DETAILS: 'schedule/SCHEDULE_DETAILS',
  EDIT_SCHEDULE: 'schedule/EDIT_SCHEDULE',
  MANAGE_PARTICIPANTS: 'schedule/MANAGE_PARTICIPANTS',
  LEAVE_SCHEDULE: 'schedule/LEAVE_SCHEDULE',
  DELETE_SCHEDULE: 'schedule/DELETE_SCHEDULE',
  CREATE_VISIT: 'visits/CREATE_VISIT',
};
